-- Hyprland Lua configuration is split by concern under configs/.
require("configs.monitors")
require("configs.programs")
require("configs.autostart")
require("configs.environment")
require("configs.permissions")
require("configs.appearance")
require("configs.input")
require("configs.bindings")
require("configs.rules")
