config_version = 12

[bar.default]
center = [ "clock", "audio_visualizer" ]
font_family = "Monofur Nerd Font"
position = "bottom"
start = [ "workspaces", "launcher", "wallpaper", "cpu" ]
thickness = 40

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[keybinds]
down = [ "Down", "Alt+j", "Alt+n" ]
left = [ "Left", "Alt+h" ]
right = [ "Right", "Alt+l" ]
up = [ "Up", "Alt+k", "Alt+p" ]

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[osd.kinds]
media = false

[shell]
font_family = "Monofur Nerd Font"

    [shell.launcher.providers.emoji]
    global = true

    [shell.launcher.providers.session]
    global = false

    [shell.launcher.providers.wallpaper]
    global = true
    prefix = ""

    [shell.launcher.providers.windows]
    global = false

    [shell.panel]
    launcher_position = "bottom_center"
    transparency_mode = "glass"

[theme]
builtin = "Catppuccin"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "faithful"

    [theme.templates]
    builtin_ids = [ "btop", "ghostty" ]
    community_ids = [ "opencode", "zen-browser", "neovim", "vscode", "fuzzel", "papirus-icons" ]

[wallpaper]
directory = "/home/sakthi/Pictures/Wallpapers"
fill_mode = "fit"

    [wallpaper.default]
    path = "/home/sakthi/Pictures/Wallpapers/moon.png"

    [wallpaper.last]
    path = "/home/sakthi/Pictures/Wallpapers/moon.png"

    [wallpaper.monitors.HDMI-A-2]
    path = "/home/sakthi/Pictures/Wallpapers/moon.png"