set -g base-index 1
set -g mouse on

# Ctrl + a for tmux leader
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Set the tmux bar on top
set-option -g status-position top

# ================================
# Interface and Looks
# ================================

# List of plugins
set -g @plugin 'omerxx/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tpm'

set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator "  █"

set -g @catppuccin_window_default_fill "number"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#{window_name}"

set -g @catppuccin_status_modules_right "application session date_time"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "yes"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
